---
title: Cipta Media Ekspresi
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Halaman pembuka Cipta Media Ekspresi, Perayaan pengetahuan dan kreatifitas
  ekspresi perempuan dalam aneka ragam bentuk dan dinamikanya dengan rupa hibah dana
  tunai.
keywords: Seni, Budaya, Perempuan, Karya, Hibah, Ford Foundation
disqus:
  name: nama_disini
  public_key: public_key_disini
ga:
  id: ga_disini
encoding: utf-8
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
